##########################################################
#
#  _____
# |__  /___ _ __  _ __  _   _
#   / // _ \ '_ \| '_ \| | | |
#  / /|  __/ |_) | |_) | |_| |
# /____\___| .__/| .__/ \__, |
#          |_|   |_|    |___/
#
#    MaceControl Plugin by Zeppy
#    Config file — please do not delete or modify badly
#    GitHub - https://github.com/MrZeppy/MaceControl.git
##########################################################

# === CORE SETTINGS ===
max-mace-count: 5
mace-command-cooldown: 5 # in seconds


# === PERMISSIONS ===
# Who can bypass mace limits and restrictions
bypass-permission: "macecontrol.bypass"
admin-permission: "macecontrol.admin"


# === RESTRICTIONS ===
restrictions:
  # Prevent maces from being put in containers
  block-containers: true

  # Prevent maces from being put on armor stands
  block-armor-stands: true

  # Prevent maces from being put in item frames
  block-item-frames: true

  # Prevent maces from being put in bundles
  block-bundles: true

  # Prevent heavy cores from being put in auto crafters
  block-heavy-core-autocrafter: true

  # Allow maces in ender chests (since they're player-specific)
  allow-ender-chest: false

  # Allow maces in shulker boxes
  allow-shulker-boxes: false


# === WORLD SETTINGS ===
worlds:
  # Worlds where mace crafting is allowed (empty = all worlds)
  allowed-craft-worlds: []

  # Worlds where mace restrictions apply (empty = all worlds)
  restricted-worlds: []


# === NOTIFICATIONS ===
messages:
  # Broadcast when a mace is destroyed/lost
  broadcast-destruction: true

  # Notify when someone crafts a mace
  broadcast-craft: true



